# MCU name
MCU = STM32F401
# MCU = STM32F411
BOOTLOADER = stm32-dfu
LTO_ENABLE = yes
OPT = 3

# QMK Features
CONSOLE_ENABLE = no
ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
NKRO_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
WPM_ENABLE = yes
SERIAL_DRIVER = usart
SPLIT_KEYBOARD = yes
POINTING_DEVICE_ENABLE = yes
DEBOUNCE_TYPE = asym_eager_defer_pk
